In [7]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [9]:
train_df = pd.read_csv('train_df.csv', index_col=0)
train_df.head()

,customer_id,product_parent,star_rating_x,"('review_id', 'count')_x","('star_rating', 'mean')_x","('star_rating', 'std')_x","('total_votes', 'mean')_x","('total_votes', 'std')_x","('helpful_votes', 'mean')_x","('helpful_votes', 'std')_x","('review_id_y', 'count')","('star_rating_y', 'mean')","('star_rating_y', 'std')","('total_votes_y', 'mean')","('total_votes_y', 'std')","('helpful_votes_y', 'mean')","('helpful_votes_y', 'std')"
0,1617361,849246716,5,5,5.000000,0.000000,0.200000,0.447214,0.000000,0.000000,297,4.872054,0.363625,0.424242,3.224979,0.37037,3.042081
1,53052607,849246716,3,5,3.600000,0.547723,0.400000,0.894427,0.400000,0.894427,297,4.872054,0.363625,0.424242,3.224979,0.37037,3.042081
2,15679577,849246716,5,8,3.375000,1.505941,7.625000,19.175412,6.500000,17.188036,297,4.872054,0.363625,0.424242,3.224979,0.37037,3.042081
3,16367779,849246716,5,9,4.444444,0.527046,0.888889,1.364225,0.777778,1.092906,297,4.872054,0.363625,0.424242,3.224979,0.37037,3.042081
4,25485198,849246716,5,17,5.000000,0.000000,0.235294,0.437237,0.176471,0.392953,297,4.872054,0.363625,0.424242,3.224979,0.37037,3.042081

In [10]:
test_df = pd.read_csv('test_df.csv', index_col=0)
test_df.head()

,customer_id,product_parent,star_rating_x,"('review_id', 'count')_x","('star_rating', 'mean')_x","('star_rating', 'std')_x","('total_votes', 'mean')_x","('total_votes', 'std')_x","('helpful_votes', 'mean')_x","('helpful_votes', 'std')_x","('review_id_y', 'count')","('star_rating_y', 'mean')","('star_rating_y', 'std')","('total_votes_y', 'mean')","('total_votes_y', 'std')","('helpful_votes_y', 'mean')","('helpful_votes_y', 'std')"
0,36330222,986428010,5,24,4.291667,1.267629,0.541667,1.250362,0.333333,1.049500,18,4.333333,1.188177,0.833333,2.572479,0.722222,2.346601
1,24360083,986428010,4,23,4.347826,1.191206,1.434783,2.191431,1.000000,1.537412,18,4.333333,1.188177,0.833333,2.572479,0.722222,2.346601
2,28891040,437083384,4,10,4.500000,0.707107,0.000000,0.000000,0.000000,0.000000,407,4.503686,0.887439,12.356265,112.878540,10.651106,100.388954
3,52449052,437083384,3,5,3.400000,1.516575,11.800000,20.789420,10.400000,18.187908,407,4.503686,0.887439,12.356265,112.878540,10.651106,100.388954
4,27192976,437083384,4,6,4.666667,0.816497,0.500000,1.224745,0.000000,0.000000,407,4.503686,0.887439,12.356265,112.878540,10.651106,100.388954

In [15]:
train_x, train_y = train_df.drop('star_rating_x', axis=1), train_df['star_rating_x']
test_x, test_y = test_df.drop('star_rating_x', axis=1), test_df['star_rating_x']

In [16]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [13]:
rf.score(test_x, test_y)

0.5808903365906624

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_x, train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [19]:
knn.score(test_x, test_y)

0.4836916395222584

In [20]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_x, train_y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [21]:
gnb.score(train_x, train_y)

0.634831542154346